### ISSUE TITLE
Allgemeinen Theorieteil sammeln

### ISSUE THREAD

**Issue by niklasbuechner** [niklasbuechner/iws#9]

**Comment by niklasbuechner** [comment]
1. Fachlich / Technisch @baris2 

2. Kapitel @Jsh250 
  - interne / externe
  - was ist DSL

**Comment by baris2** [comment]
Was ist eine Domäne?
- bestimmter Problembereich
- Problemfeld
- z.B. Beschreibung von Regeln für den Aufbau von Zeichenfolgen mit regulären Ausdrücken als passende DSL

Unterscheidungen in der Domäne der "Softwareentwicklung"
"fachliche / abstrahierende DSLs" / "application domain "DSLs"
- DSLs zur abstrakteren Entwicklung eines Programms, diese vereinfachen die Implementierung des Programms,
  indem sie die Semantik des Codes von technischen Details der Zielplattform entkoppeln. Diese werden daher oft für Prototyping
  und zur Entwicklung von möglichst plattformunabhängigen Code verwendet.
- Verwender sind hierbei die nicht-Programmierer, die Affinität in der Domäne besitzen
- Einfache Sprache die z.B SQL ausgibt (Ermöglicht dem domänenaffinien Benutzer 
  
"technische DSLs" / "technical DSLs"
- DSLs zur vereinfachten Handhabung der technischen Aspekte der Implementierung (kurch technische DSLs) hingegen vereinfachen die
  zusätzlich zur Implementierung aufallenden Arbeiten wie z.B. Code-Dokumentation, Tests und Parallelisierung die unabhängig von der
  domänenspezifischen Semantik des Quellcodes sind. Technische DSLs wie z.B XML werden darüber hinaus oft für den Austausch von Informationen
  zwischen verschiedenen Anwendungen verwendet.
- Verwender sind in diesem Fall die Entwickler selbst
- CSS
- HTML
- SQL
